# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale: "en-US"
title: "Hrishikesh Nirgude"
title_separator: "-"
name: &name "Hrishikesh Nirgude's Website"
description: &description "personal description"
url: https://hrishi109.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "Hrishi109/Hrishi109.github.io"
teaser: # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs: false # true, false (default)
words_per_minute: 160
future: true
read_more: "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link: false #change to true to add link to talkmap on talks page
comments:
  provider: "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname: "Hrishi"
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"
staticman:
  allowedFields: ["name", "email", "url", "message"]
  branch: "gh-pages" # "master", "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ["name", "email", "message"]
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path: # blank (default) uses feed.xml

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username: &twitter
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "UA—163839465-1"

google_analytics: UA—163839465-1

# Site Author
author:
  name: "Hrishikesh Nirgude"
  avatar: "---
layout: archive
title: "About Me"
permalink: /about_me/
author_profile: true
redirect_from:
  - /extracurricular-activities
---

# About Me

Welcome to my corner of the internet! I am a curious, passionate individual constantly inspired by the world around me. Whether it's engineering challenges, the harmony of music, or the serenity of nature, I find joy in exploring, creating, and connecting.

## Interests and Hobbies:

### Sports:
#### Cricket
Cricket has been a lifelong companion, blending strategy, patience, and bursts of brilliance. From the joy of a perfectly timed cover drive to the rush of facing a fierce bowler, cricket has taught me discipline, teamwork, and perseverance. My time as an opening batsman honed my ability to stay calm under pressure and seize opportunities—a mindset I carry into all areas of life.

#### Badminton and Table Tennis
The thrill of a sharp rally in badminton or the lightning reflexes needed for table tennis make these sports both exhilarating and grounding. Whether playing for leisure or challenging a worthy opponent, I love the way these games test not only physical agility but also mental sharpness.

#### Formula 1
Few things captivate me like the world of Formula 1. The roar of engines, the brilliance of engineering, and the tactical genius displayed on race day are truly inspiring. I admire how every millisecond matters, from adjusting front-wing angles to designing groundbreaking systems like Mercedes' DAS. Following F1 has deepened my appreciation for teamwork, innovation, and the relentless pursuit of excellence.

#### Swimming
Gliding through water feels like freedom. Swimming has been my sanctuary—a space where my mind quiets, my body moves in rhythm, and every stroke brings a sense of calm and clarity. It's a sport that has built my endurance and instilled in me a love for pushing my limits.

---

### Music:
#### Playing Guitar and Piano
Music is a universal language, and for me, it speaks volumes. My journey with music began with the piano, learning its complexities and discovering how melodies can evoke powerful emotions. The guitar, with its soulful strings, became an extension of my creativity during the pandemic. Building my own electric guitar was a deeply rewarding project, blending my love for engineering with my passion for music. 

I find joy in exploring a variety of genres, from the soulful ballads of Pink Floyd to the electrifying energy of Led Zeppelin. Playing music allows me to express myself in ways words cannot, and I’m currently working on mastering "Stairway to Heaven" across multiple instruments.

---

### Adventure:
#### Hiking
There’s something magical about standing on a mountaintop, feeling the cool breeze and taking in breathtaking views after a challenging hike. Hiking has taught me to embrace the journey as much as the destination. It’s a wonderful way to reconnect with nature, recharge my spirit, and find inspiration in the beauty of the world around us.

---

### Creativity:
#### Astrophotography
Staring at the night sky has always sparked my curiosity about the cosmos. Through astrophotography, I’ve been able to capture the beauty of distant galaxies, nebulae, and constellations. It’s incredible how a simple telescope and a camera can reveal the wonders of the universe. This hobby reminds me of the limitless possibilities of exploration and the small but significant role we play in the grand scheme of things.

#### Sketching
Sketching has been a source of joy and mindfulness for me. I particularly enjoy drawing fictional characters, bringing them to life with my own unique perspective. The process of sketching sharpens my attention to detail and allows me to appreciate the artistry in everyday life. Many of my sketches are from my childhood and pandemic days, serving as a creative outlet during challenging times.

---

### Languages:
I’ve always been fascinated by the power of language to connect people and cultures. I am fluent in six languages: English, German, Konkani, Marathi, Hindi, and Kannada. I can also understand French and am eager to improve my fluency. Learning new languages like Sanskrit, Italian, and Spanish is a goal I hold dear, as it broadens my worldview and deepens my appreciation for the diversity of human expression.

---

## Contact Me:
I am always open to connecting with like-minded individuals! Whether it’s a conversation about sports strategies, a jam session with music enthusiasts, a shared love for hiking trails, or exchanging thoughts on astrophotography and sketching, I’d love to hear from you. Feel free to reach out—let’s create, collaborate, and grow together!
png"
  bio: "Mechatronics-Robotics Masters Student at Worcester Polytechnic Institute"
  location: "Worcester, MA"
  email: "hnirgude@wpi.edu"
  # researchgate: # example: "https://www.researchgate.net/profile/yourprofile"
  # uri:
  github: "Hrishi109"
  instagram: "https://www.instagram.com/nsidn98_/"
  impactstory: #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
    linkedin: "https://www.linkedin.com/in/hrishikesh-nirgude19071998/"



# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Calcutta

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
